from .artifact_analyzer import (
    NODE_CLASS_MAPPINGS as _ANALYZER_NODES,
    NODE_DISPLAY_NAME_MAPPINGS as _ANALYZER_NAMES,
)
from .artifact_cleaner import (
    NODE_CLASS_MAPPINGS as _CLEANER_NODES,
    NODE_DISPLAY_NAME_MAPPINGS as _CLEANER_NAMES,
)

NODE_CLASS_MAPPINGS = {**_ANALYZER_NODES, **_CLEANER_NODES}
NODE_DISPLAY_NAME_MAPPINGS = {**_ANALYZER_NAMES, **_CLEANER_NAMES}

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
